/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.LocalEPA;

import Business.EcoSystem;
import Business.Employee.Citizen;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CitizensOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.VitalSign.VitalSign;
import Business.VitalSign.VitalSignHistory;
import Business.WorkRequest.WorkRequest;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author jinliyu
 */
public class SendWarningMessageJPanel extends javax.swing.JPanel {
private JPanel upc;
private Network city;
private UserAccount account;
private Organization organization;
private EcoSystem system;
    /**
     * Creates new form SendWarningMessageJPanel
     */
    public SendWarningMessageJPanel(JPanel upc,UserAccount account, Organization o,EcoSystem system) {
        initComponents();
        this.account = account;
        this.upc = upc;
        this.system =system;
        this.organization=o;
        populateComboBox();
    }
    
    public void populateComboBox(){
    ComboBox.removeAllItems();
    ComboBox.addItem("people over 70");
    ComboBox.addItem("people who have heart diseases");
    ComboBox.addItem("people who have diabete");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 16)); // NOI18N
        jLabel1.setText("Select group of people:");

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 0, 16)); // NOI18N
        jLabel2.setText("Message:");

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(36, 36, 36)
                                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(40, 40, 40)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        String message = jTextField1.getText();
        
        WorkRequest request = new WorkRequest();
        request.setMessage(message);
        request.setSender("LocalEPA");
        request.setSendDate(new Date());
       
        
        Organization org = null;
        for (Network nw : system.getNetworkList()){
            for(Enterprise e: nw.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organization o:e.getOrganizationDirectory().getOrganizationList())
            if (o instanceof CitizensOrganization){
                org = o;
                
                String target = (String)ComboBox.getSelectedItem();
                if(target.equals("people over 70"))
                    for(UserAccount ua:org.getUserAccountDirectory().getUserAccountList()){
                        Citizen citizen =(Citizen)ua.getEmployee();
                        if(citizen.getAge()>=70)
                        { ua.getWorkQueue().getWorkRequestList().add(request);}
                    }
             
                else if(target.equals("people who have heart diseases"))     
                    for(UserAccount ua:org.getUserAccountDirectory().getUserAccountList()){
                        Citizen citizen =(Citizen)ua.getEmployee();
                              VitalSignHistory vsh = citizen.getVitalSignHistory();
                        VitalSign vs = vsh.getVitalSignHistory().get(vsh.getVitalSignHistory().size() - 1);
                        if(vs.getIsHeartRateNormal().equals("Abnormal"))
                        { ua.getWorkQueue().getWorkRequestList().add(request);}
                    }
                
                else if(target.equals("people who have diabete"))     
                    for(UserAccount ua:org.getUserAccountDirectory().getUserAccountList()){
                        Citizen citizen =(Citizen)ua.getEmployee();
                              VitalSignHistory vsh = citizen.getVitalSignHistory();
                        VitalSign vs = vsh.getVitalSignHistory().get(vsh.getVitalSignHistory().size() - 1);
                        if(vs.getIsDiabete().equals("Yes"))
                        { ua.getWorkQueue().getWorkRequestList().add(request);}
                    }
                
            }
            }
        }
//       if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(request);
           account.getWorkQueue().getWorkRequestList().add(request);
//        }
        
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
