/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.AirMonitor;

import Business.AirCondition.AirCondition;
import Business.AirCondition.AirConditionDirectory;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author jinliyu
 */
public class AcquireJPanel extends javax.swing.JPanel {
private JPanel upc;
private Network network;
private Enterprise enterprise;
    /**
     * Creates new form AcquireJPanel
     */
    public AcquireJPanel(JPanel upc, Enterprise enterprise, Network network) {
        initComponents();
        this.network = network;
        this.upc = upc;
        this.enterprise = enterprise;
        populateTable();
    }
public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) aqiTable.getModel();
        model.setRowCount(0);
         AirConditionDirectory acd = network.getAirConditionDirectory();
         
        for (AirCondition ac : network.getAirConditionDirectory().getAirConditonList()) {
            
            Object[] row = new Object[2];
            int a = acd.getAirConditonList().indexOf(ac);
            row[0] = a+1;
            row[1] = ac.getAqi();
            model.addRow(row);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aqiTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("View graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        aqiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No.", "AQI"
            }
        ));
        jScrollPane1.setViewportView(aqiTable);

        jButton1.setText("Acquire air condition");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int time = 0;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (AirCondition ac : network.getAirConditionDirectory().getAirConditonList()) {
            time = time+1;
            dataset.setValue((Number)ac.getAqi(), "Value of AQI", time);
        }
        JFreeChart chart = ChartFactory.createLineChart("AirCondition", "Times", "AQI Number", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setBackgroundPaint(Color.PINK);
        p.setRangeGridlinePaint((Color.black));
        ChartFrame frame = new ChartFrame("bar chart for citizens' examination result", chart);
        frame.setVisible(true);
        frame.setSize(500, 400);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = 10 + (int) (Math.random() * 320);
        AirCondition ac = new AirCondition();
        ac.setAqi(x);
        network.getAirConditionDirectory().getAirConditonList().add(ac);
        populateTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aqiTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
