/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.StateOfficial;

import Business.EcoSystem;
import Business.Employee.Citizen;
import Business.Employee.Employee;
import Business.Enterprise.CitizenEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.VitalSign.VitalSign;
import Business.VitalSign.VitalSignHistory;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author jinliyu
 */
public class ViewHealthRateJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private EcoSystem system;

    /**
     * Creates new form ViewHealthRateJPanel
     */
    public ViewHealthRateJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.system = system;
        this.upc = upc;
        populateComboBox();
    }

    public void populateComboBox() {
        CityComboBox.removeAllItems();
        for (Network network : system.getNetworkList()) {
            CityComboBox.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CityComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        CityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Choose a city");

        jButton5.setText("<<back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Normal/Abnormal chart");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Sys Blood Pressure Result Chart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Heart Rate Collection Result chart");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Weight Result Chart");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addComponent(CityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jButton5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(151, 151, 151)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int num = 0;
        int normalNum = 0;
        Network network = (Network) CityComboBox.getSelectedItem();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CitizenEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
                        Citizen c = (Citizen) employee;
                        num = num + 1;
                        VitalSignHistory vsh = new VitalSignHistory();
                        VitalSign vs = c.getVitalSignHistory().getVitalSignHistory().get(vsh.getVitalSignHistory().size());
                        String result = vs.getResult();
                        if (result.equals("Normal")) {
                            normalNum = normalNum + 1;
                        }

                    }
                }
            }
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(normalNum, "Number", "Normal");
        dataset.setValue(num - normalNum, "Number", "Abnormal");
        JFreeChart chart = ChartFactory.createBarChart("Citizens' Health Examination Result", "Result", "Number", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint((Color.black));
        ChartFrame frame= new ChartFrame("bar chart for citizens' examination result", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int num = 0;
        int normalNum = 0;
        Network network = (Network) CityComboBox.getSelectedItem();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CitizenEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
                        Citizen c = (Citizen) employee;
                        num = num + 1;
                        VitalSignHistory vsh = new VitalSignHistory();
                        VitalSign vs = c.getVitalSignHistory().getVitalSignHistory().get(vsh.getVitalSignHistory().size());
                        String result = vs.getIsHeartRateNormal();
                        if (result.equals("Normal")) {
                            normalNum = normalNum + 1;
                        }

                    }
                }
            }
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(normalNum, "Number", "Normal");
        dataset.setValue(num - normalNum, "Number", "Abnormal");
        JFreeChart chart = ChartFactory.createBarChart("Citizens' Heart Rate Examination Result", "Result", "Number", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint((Color.black));
        ChartFrame frame= new ChartFrame("bar chart for citizens' Heart Rate examination result", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int num = 0;
        int normalNum = 0;
        Network network = (Network) CityComboBox.getSelectedItem();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CitizenEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
                        Citizen c = (Citizen) employee;
                        num = num + 1;
                        VitalSignHistory vsh = new VitalSignHistory();
                        VitalSign vs = c.getVitalSignHistory().getVitalSignHistory().get(vsh.getVitalSignHistory().size());
                        String result = vs.getIsBloodPressureNormal();
                        if (result.equals("Normal")) {
                            normalNum = normalNum + 1;
                        }

                    }
                }
            }
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(normalNum, "Number", "Normal");
        dataset.setValue(num - normalNum, "Number", "Abnormal");
        JFreeChart chart = ChartFactory.createBarChart("Citizens' SysbloodPressure Examination Resultt", "Result", "Number", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint((Color.black));
        ChartFrame frame= new ChartFrame("bar chart for Citizens' SysbloodPressure Examination Result", chart);
        frame.setVisible(true);
        frame.setSize(450, 350); // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int num = 0;
        int normalNum = 0;
         Network network = (Network) CityComboBox.getSelectedItem();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CitizenEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
                        Citizen c = (Citizen) employee;
                        num = num + 1;
                        VitalSignHistory vsh = new VitalSignHistory();
                        VitalSign vs = c.getVitalSignHistory().getVitalSignHistory().get(vsh.getVitalSignHistory().size());
                        String result = vs.getIsWeightNormal();
                        if (result.equals("Normal")||result.equals("/")) {
                            normalNum = normalNum + 1;
                        }

                    }
                }
            }
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(normalNum, "Number", "Normal");
        dataset.setValue(num - normalNum, "Number", "Abnormal");
        JFreeChart chart = ChartFactory.createBarChart("Citizens' Weight Examination Result", "Result", "Number", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint((Color.black));
        ChartFrame frame= new ChartFrame("bar chart for citizens' weight examination result", chart);
        frame.setVisible(true);
        frame.setSize(450, 350); // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CityComboBox;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
